name = "Soundcore R50i NC"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7B395B"

[[responses]]
# State update
command = [1, 1]
response = [
    1,
    1,
    5,
    6,
    255,
    255,
    48,
    49,
    46,
    54,
    52,
    48,
    49,
    46,
    54,
    52,
    51,
    57,
    53,
    57,
    68,
    69,
    68,
    54,
    54,
    57,
    50,
    68,
    66,
    54,
    70,
    52,
    254,
    254,
    101,
    120,
    161,
    171,
    171,
    152,
    144,
    179,
    120,
    120,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    10,
    241,
    240,
    102,
    102,
    242,
    243,
    68,
    68,
    51,
    0,
    85,
    0,
    0,
    1,
    255,
    1,
    49,
    1,
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
]
