[workspace]
members = ["cli", "gui", "lib", "android", "web/wasm", "tokio_rt_multi_thread"]
resolver = "2"

[profile.release]
strip = true
lto = true

[profile.release-debuginfo]
inherits = "release"
strip = false
debug = 2
