[workspace]
members = ["cli", "gui", "lib", "lib_protobuf", "android", "web/wasm", "uniffi-bindgen"]
resolver = "2"

[profile.release]
strip = true
lto = true

[profile.release-debuginfo]
inherits = "release"
strip = false
debug = 2
