[package]
name = "openscq30_web_wasm"
description = "Packet parsing and such for OpenSCQ30 web"
repository = "https://github.com/Oppzippy/OpenSCQ30/tree/master/web/wasm"
license = "GPL-3.0-or-later"
version = "1.3.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
openscq30_lib = { path = "../../lib" }
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.5"
