[tasks.test]
clear = true
dependencies = ["unit-test"]

[tasks.unit-test]
command = "cargo"
env = { "RUSTFLAGS" = "--cfg=web_sys_unstable_apis" }
args = ["test", "--lib"]

[tasks.unit-test-cov]
command = "cargo"
env = { "RUSTFLAGS" = "--cfg=web_sys_unstable_apis" }
args = ["llvm-cov", "--no-report", "--lib"]
