[package]
name = "openscq30_gui"
version = "1.9.0"
edition = "2021"

[features]
default = ["bluetooth"]
bluetooth = ["openscq30_lib/bluetooth"]
demo = ["openscq30_lib/demo"]

[dependencies]
openscq30_lib = { path = "../lib", features = ["serde"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
futures = { version = "0.3" }
tracing = "0.1"
tracing-subscriber = "0.3"
adw = { version = "0.5", package = "libadwaita", features = ["v1_4"] }
gtk = { version = "0.7", package = "gtk4", features = ["gnome_44"] }
strum = { version = "0.25", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
anyhow = { version = "1.0" }
once_cell = "1.19"
heck = "0.4"
dirs = "5"
macaddr = "1.0"
itertools = "0.12"
uuid = { version = "1", features = ["serde"] }

[dev-dependencies]
mockall = "0.11.2"
tempfile = "3.4"

[build-dependencies]
glib-build-tools = "0.17"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "2.0.0"
tempfile = "3.4"
regex = "1.7"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.48", features = ["Foundation", "UI_ViewManagement"] }
