[package]
name = "openscq30_cli"
version.workspace = true
license.workspace = true
edition = "2021"

[features]
default = ["bluetooth"]
bluetooth = ["openscq30_lib/bluetooth"]

[dependencies]
openscq30_lib = { path = "../lib" }
clap = { workspace = true, features = ["derive"] }
clap_complete = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
macaddr = { workspace = true }
heck = { workspace = true }
itertools = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
