[package]
name = "openscq30_cli"
version.workspace = true
license.workspace = true
edition = "2021"

[features]
default = ["bluetooth"]
bluetooth = ["openscq30_lib/bluetooth"]
demo = ["openscq30_lib/demo"]

[dependencies]
openscq30_lib = { path = "../lib" }
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
macaddr = "1.0"
heck = "0.4"
itertools = "0.12"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
