extend = "../Makefile.toml"

[tasks.build]
script.main = '''
cm_run_task build-bin
'''

[tasks.build-bin]
private = true
command = "cargo"
args = ["build", "@@split(OPENSCQ30_BUILD_FLAGS, )"]

[tasks.unit-test]
command = "cargo"
args = ["test", "--bins"]

[tasks.integration-test]
command = "cargo"
args = ["test", "--no-default-features", "--features", "demo", "--test", "*"]

[tasks.unit-test-cov]
command = "cargo"
args = ["llvm-cov", "--no-report", "--bins"]

[tasks.integration-test-cov]
command = "cargo"
args = [
    "llvm-cov",
    "--no-report",
    "--no-default-features",
    "--features",
    "demo",
    "--test",
    "*",
]

[tasks.install]
condition.platforms = ["linux"]
script.main = '''
bin_path = set ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/release/openscq30_cli
is_bin_built = is_file ${bin_path}
if not ${is_bin_built}
    echo Run `cargo make --profile release build` before installing.
    exit 1
end

echo Installing binary
cp ${bin_path} ${INSTALL_PREFIX}/bin/openscq30_cli
chmod 755 ${INSTALL_PREFIX}/bin/openscq30_cli

if is_path_exists ${INSTALL_PREFIX}/share/bash-completions/completions
    echo Installing bash completions
    output = exec ${bin_path} completions bash
    bash_completions = set ${output.stdout}
    writefile ${INSTALL_PREFIX}/share/bash-completions/completions/openscq30_cli ${bash_completions}
end
'''

[tasks.uninstall]
condition.platforms = ["linux"]
script.main = '''
echo Removing binary
rm ${INSTALL_PREFIX}/bin/openscq30_cli
echo Removing bash completions
rm ${INSTALL_PREFIX}/share/bash-completions/completions/openscq30_cli
'''
