extend = "../Makefile.toml"

[tasks.build]
script.main = '''
cm_run_task build-bin
'''

[tasks.build-bin]
private = true
command = "cargo"
args = ["build", "@@split(OPENSCQ30_BUILD_FLAGS, )"]

[tasks.unit-test]
command = "cargo"
args = ["test", "--bins"]

[tasks.integration-test]
command = "cargo"
args = ["test", "--no-default-features", "--features", "demo", "--test", "*"]

[tasks.unit-test-cov]
command = "cargo"
args = ["llvm-cov", "--no-report", "--bins"]

[tasks.integration-test-cov]
command = "cargo"
args = [
    "llvm-cov",
    "--no-report",
    "--no-default-features",
    "--features",
    "demo",
    "--test",
    "*",
]

[tasks.install]
condition.platforms = ["linux"]
script.main = '''
echo Installing binary
cp ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/release/openscq30_cli ${INSTALL_PREFIX}/bin/openscq30_cli
chmod 755 ${INSTALL_PREFIX}/bin/openscq30_cli
'''

[tasks.uninstall]
condition.platforms = ["linux"]
script.main = '''
echo Removing binary
rm ${INSTALL_PREFIX}/bin/openscq30_cli
'''
