name = "Soundcore Life Q30"
rfcomm_uuid = "00001101-0000-1000-8000-00805f9b34fb"

[[responses]]
# State update
command = [1, 1]
response = [
    9,
    255,
    0,
    0,
    1,
    1,
    1,   # command
    77,
    0,   # length
    5,
    0,   # battery
    14,
    0,
    120,
    150,
    150,
    140,
    160,
    170,
    150,
    160, # equalizer configuration
    0,   #gender
    0,   #age range
    0,   # hear id is enabled
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,   # hear id left
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,   # hear id right
    0,
    0,
    0,
    0,   # hear id time
    0,
    0,
    0,
    0,   # sound modes
    48,
    52,
    46,
    51,
    51,  # firmware version
    51,
    48,
    50,
    56,
    54,
    68,
    67,
    56,
    57,
    51,
    52,
    52,
    52,
    55,
    57,
    56,  # serial number
    0,
    0,
    1,
    1,
    1,
    1,
    1,   # 7 optional unknown bools ???
    138, # checksum
]
