[package]
name = "openscq30_android"
version = "1.6.0"
edition = "2021"

[dependencies]
openscq30_lib = { path = "../lib" }
tracing = { version = "0.1", features = ["log-always"] }
rifgen = { path = "../rifgen" }
jni-sys = "0.3.0"
log = "0.4"
tokio = { version = "1", features = ["rt-multi-thread"] }
thiserror = "1.0"
android_logger = "0.13.0"
anyhow = "1.0.69"
macaddr = "1.0.1"
uuid = "1.3"
itertools = "0.11"

[build-dependencies]
flapigen = "0.6.0"
rifgen = { path = "../rifgen" }

[lib]
crate-type = ["cdylib"]
