[package]
name = "openscq30_android"
version = "0.1.0"
edition = "2021"

[dependencies]
openscq30_lib = { path = "../lib", features = ["btleplug"] }
tracing = { version = "0.1", features = ["log-always"] }
rifgen = "0.1.61"
jni-sys = "0.3.0"
log = "0.4"
tokio = { version = "1", features = ["rt-multi-thread"] }
thiserror = "1.0"
android_logger = "0.11.3"

[build-dependencies]
flapigen = "0.6.0-pre13"
rifgen = "0.1.61"

[lib]
crate-type = ["cdylib"]
