[bindings.kotlin]
package_name = "com.oppzippy.openscq30.lib.bindings"

[bindings.kotlin.custom_types.Uuid]
type_name = "UUID"
imports = ["java.util.UUID"]
into_custom = "UUID.fromString({})"
from_custom = "{}.toString()"
