name: "android: test"

on:
  - push

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7-linux-androideabi,aarch64-linux-android,i686-linux-android,x86_64-linux-android
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Run android unit tests
        working-directory: android
        run: ./gradlew test
      # - name: Run android instrumented tests
      #   working-directory: android
      #   run: ./gradlew connectedAndroidTest
