name: "build"

on:
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install basic requirements
        run: sudo apt-get install just
      - uses: dtolnay/rust-toolchain@stable
      - name: Build cli
        run: cargo build --release --package openscq30-cli
      - name: Build gui
        run: cargo build --release --package openscq30-gui

      - name: Move to artifacts directory
        run: |
          mkdir artifacts
          mv target/release/openscq30 artifacts/openscq30-cli-linux-x86_64
          mv target/release/openscq30-gui artifacts/openscq30-gui-linux-x86_64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: artifacts/*

  build_windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install basic requirements
        run: sudo apt-get install just
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu
      - name: Build cli
        run: cargo build --target x86_64-pc-windows-gnu --release --package openscq30-cli
      - name: Build gui
        run: cargo build --target x86_64-pc-windows-gnu --release --package openscq30-gui

      - name: Move to artifacts directory
        run: |
          mkdir artifacts
          mv target/release/openscq30 artifacts/openscq30-cli-linux-x86_64
          mv target/release/openscq30-gui artifacts/openscq30-gui-linux-x86_64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: artifacts/*

  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install build tools
        uses: ./.github/actions/install-android-build-tools
        with:
          cache: false

      - name: Build
        run: ./gradlew --no-daemon assembleBluetoothRelease
        working-directory: android
      - name: Rename apk
        run: mv android/app/build/outputs/apk/bluetooth/release/app-bluetooth-release-unsigned.apk openscq30-android.apk
      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: openscq30-android.apk
