name: "lint"

on:
  - push

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        components: rustfmt
      - name: Check formatting
        run: cargo fmt --check
