name: "rust: test"

on:
  - push

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies from apt
        run: sudo apt-get install libdbus-1-dev pkg-config libgtk-4-dev libadwaita-1-dev
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run rust tests
        run: cargo test
