name: "test"

on:
  - push

jobs:
  rust_test_linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies from apt
        run: |
          sudo apt-get update
          sudo apt-get install libdbus-1-dev pkg-config libgtk-4-dev libadwaita-1-dev
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run rust tests
        run: cargo test
      - name: Run rust tests in demo mode
        run: cargo test --features demo

  # Only lib is tested on windows since building gtk takes too long, and lib is the only crate with os specific code
  rust_test_windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run rust tests
        run: cargo test --package openscq30_lib

  android_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv7-linux-androideabi,aarch64-linux-android,i686-linux-android,x86_64-linux-android
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-ndk
        run: cargo install cargo-ndk

      - name: Run android unit tests
        working-directory: android
        run: ./gradlew test
      # - name: Run android instrumented tests
      #   working-directory: android
      #   run: ./gradlew connectedAndroidTest
